name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_messaging: ^11.2.12
  cloud_firestore: ^3.1.11
  modal_progress_hud: ^0.1.3
  firebase_analytics: ^9.1.4
  device_preview: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
